version: '2'

services:
  adapter:
    image: registry.sonata-nfv.eu:5000/son-gtkusr
    ports:
      - "5600:5600"
    links:
     - keycloak
     - mongo:mongo
    environment:
      - KEYCLOAK_ADDRESS=son-keycloak
      - KEYCLOAK_PORT=5601
      - KEYCLOAK_PATH=auth
      - SONATA_REALM=sonata
      - CLIENT_NAME=adapter
    container_name: son-gtkusr
  keycloak:
    image: registry.sonata-nfv.eu:5000/son-keycloak
    ports:
      - "5601:5601"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - SONATA_USER=sonata
      - SONATA_PASSWORD=1234
      - SONATA_EMAIL=sonata.admin@email.com
    container_name: son-keycloak
  mongodata-gtk:
    image: mongo:3.0.4
    volumes:
      - /data/db
    command: --break-mongo
  mongo:
    image: mongo:3.0.4
    volumes_from:
      - mongodata-gtk
    ports:
      - "27017"
    command: --smallfiles --rest
    restart: always
