version: '2'

services:
  adapter:
    image: registry.sonata-nfv.eu:5000/son-gtkusr
    ports:
      - "5600:5600"
    links:
     - keycloak
    environment:
      - KEYCLOAK_ADDRESS=keycloak
      - KEYCLOAK_PORT=5601
      - KEYCLOAK_PATH=auth
      - SONATA_REALM=sonata
      - CLIENT_NAME=adapter
    container_name: son-gtkusr
  keycloak:
    image: registry.sonata-nfv.eu:5000/son-gtkusr-keycloak
    ports:
      - "5601:5601"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    container_name: sonata-keycloak
